require File.expand_path('../../node_modules/@capacitor/ios/scripts/pods_helpers.rb', __dir__)

platform :ios, '16.0'
use_frameworks!
use_modular_headers!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
  pod 'CapacitorFirebaseMessaging', :path => '../../node_modules/@capacitor-firebase/messaging'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
